//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danh_sách_sinh_viên
    {
        public string mahocvien { get; set; }
        public string tenhocvien { get; set; }
        public string lop { get; set; }
        public string khoa_khoi { get; set; }
        public string doituong { get; set; }
        public string sdt { get; set; }
        public Nullable<System.DateTime> ngaynhaphoc { get; set; }
        public Nullable<int> hocphi { get; set; }
        public string trangthai { get; set; }
        public string thucthu { get; set; }
        public Nullable<System.DateTime> ngaythu { get; set; }
    }
}
