//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danh_sách_môn_học
    {
        public string Mamonhoc { get; set; }
        public string Monhoc { get; set; }
        public string Khoa_khoi { get; set; }
        public Nullable<int> Donvitinh { get; set; }
        public string Trangthai { get; set; }
        public string Tonghocphi { get; set; }
        public Nullable<int> Mucthumoidonvi { get; set; }
        public Nullable<int> Nienkhoa { get; set; }
        public string Thoiluong { get; set; }
        public Nullable<int> Thoiluongmonhoc { get; set; }
        public Nullable<int> Tonghocphiphaithu { get; set; }
        public string Nienkhoa1 { get; set; }
    }
}
