//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danh_sách_giáo_viên
    {
        public string Magiangvien { get; set; }
        public string Hovaten { get; set; }
        public string Mangach { get; set; }
        public string Chucvu { get; set; }
        public string Tobomon { get; set; }
        public string Loaihopdong { get; set; }
        public Nullable<System.DateTime> Ngayvaotruong { get; set; }
        public string Nghiphep { get; set; }
        public string Trangthai { get; set; }
        public string Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<int> SoCMND { get; set; }
        public Nullable<System.DateTime> Ngaycap { get; set; }
        public string Noicap { get; set; }
        public string Diachi { get; set; }
        public string SoBHXH { get; set; }
        public string Trinhdodaotao { get; set; }
        public Nullable<System.DateTime> Ngayapdungchucvu { get; set; }
        public Nullable<System.DateTime> Ngaybatdaulamviec { get; set; }
        public string Ngach_hang { get; set; }
        public string Bacluong { get; set; }
        public string Hesoluong { get; set; }
        public Nullable<System.DateTime> Ngayapdungngachbac { get; set; }
        public string Phucap { get; set; }
        public Nullable<int> Luongcoban { get; set; }
    }
}
