//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Môn_học
    {
        public string Mamonhoc { get; set; }
        public string Monhoc { get; set; }
        public string Khoa_khoi { get; set; }
        public Nullable<int> Thoiluong { get; set; }
        public string Donvitinh { get; set; }
        public string Mucthutrendonvitinh { get; set; }
        public Nullable<decimal> Tonghocphiphaithu { get; set; }
        public string Trangthai { get; set; }
    }
}
